version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: prem_app_client
    restart: unless-stopped
    env_file:
      - ./client/.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: prem_app_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    depends_on:
      - client
  nginx:
    image: nginx
    container_name: prem_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
