version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: prem_app_client_production
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - 8000:3000
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: prem_app_server_production
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
  nginx:
    image: nginx
    container_name: prem_nginx_production
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
