version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: prem_app_client
    env_file:
      - ./client/.env
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: prem_app_server
    env_file:
      - ./server/.env
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
