import Vue from "vue";
import Vuetify from "vuetify/lib/framework";

Vue.use(Vuetify);

export default new Vuetify({
  theme: {
    themes: {
      light: {
        mardiGras: "#38003C",
        springGreen: "#00FF85",
        razzmatazz: "#E90052",
        aqua: "#04F5FF",
        arsenalRed: "#EF0107",
        arsenalWhite: "#FFFFFF",
        villaClaret: "#670E36",
        villaBlue: "#95BFE5",
        villaYello: "#FEE505",
        brightonBlue: "#005DAA",
        brightonYellow: "#FDB913",
        brentfordRed: "#E30613",
        brentfordWhite: "#FFFFFF",
        burnleyBlue: "#97D9F6",
        burnleyYellow: "#FFF30D",
        burnleyBurgundy: "#630530",
        chelseaBlue: "#034694",
        chelseaWhite: "#FFFFFF",
        palaceBlue: "#1B458F",
        palaceRed: "#C4122E",
        evertonBlue: "#274488",
        evertonWhite: "#FFFFFF",
        leicesterBlue: "#0053A0",
        leicesterWhite: "#FFFFFF",
        liverpoolRed: "#D00027",
        liverpoolGreen: "#00A398",
        leedsYellow: "#FFCD00",
        leedsBlue: "#1D428A",
        cityBlue: "#6CADDF",
        cityWhite: "FFFFFF",
        unitedRed: "#DA020E",
        unitedGold: "#FFE500",
        newcastleBlack: "#000000",
        newcastleWhite: "#FFFFFF",
        norwichGreen: "#00A650",
        norwichYellow: "#FFF200",
        saintsRed: "#ED1A3B",
        saintsGreen: "#22B24C",
        spursBlue: "#132257",
        spursWhite: "#FFFFFF",
        watfordRed: "#ED2127",
        watfordYellow: "#FBEE23",
        watfordBlack: "#000000",
        hammersMaroon: "#7C2C3B",
        hammersBlue: "#2DAFE5",
        hammersGold: "#F8D742",
        wolvesGold: "#FDB913",
        wolvesBlack: "#000000",
      },
    },
  },
});
